// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values are used if VITE environment variables are not set, ensuring the client initializes.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://sfvwxvpnjtwxcbkwqtaj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdnd4dnBuanR3eGNia3dxdGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MDAzMDQsImV4cCI6MjA3NzI3NjMwNH0.JiXA0Tms5IV8qNxpIpb2f00wGRn9c6ATWCOXZWtmX78';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});